### ISSUE TITLE
[FEATURE] Add some behat tests w/phantomjs

### ISSUE THREAD

**Issue by assertchris** [wayneashleyberry/larasites.com#49]
Do you think it would be good to move the behavioural/integration testing out of phpunit? Perhaps using [Behat and PhantomJS](http://shashikantjagtap.net/running-behat-scenarios-with-pahntomjs/)...

**Comment by assertchris** [comment]
;(

**Comment by wayneashleyberry** [comment]
@assertchris abandonware 😿
